package h.entities;
// Generated 29-Feb-2012 13:51:12 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Costplan generated by hbm2java
 */
public class Costplan  implements java.io.Serializable {


     private Integer costId;
     private Job job;
     private Totalpower totalpower;
     private Cpu cpu;
     private BigDecimal jobRevenue;
     private BigDecimal tpowerCost;
     private BigDecimal damageCost;
     private Set userses = new HashSet(0);

    public Costplan() {
    }

    public Costplan(Job job, Totalpower totalpower, Cpu cpu, BigDecimal jobRevenue, BigDecimal tpowerCost, BigDecimal damageCost, Set userses) {
       this.job = job;
       this.totalpower = totalpower;
       this.cpu = cpu;
       this.jobRevenue = jobRevenue;
       this.tpowerCost = tpowerCost;
       this.damageCost = damageCost;
       this.userses = userses;
    }
   
    public Integer getCostId() {
        return this.costId;
    }
    
    public void setCostId(Integer costId) {
        this.costId = costId;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }
    public Totalpower getTotalpower() {
        return this.totalpower;
    }
    
    public void setTotalpower(Totalpower totalpower) {
        this.totalpower = totalpower;
    }
    public Cpu getCpu() {
        return this.cpu;
    }
    
    public void setCpu(Cpu cpu) {
        this.cpu = cpu;
    }
    public BigDecimal getJobRevenue() {
        return this.jobRevenue;
    }
    
    public void setJobRevenue(BigDecimal jobRevenue) {
        this.jobRevenue = jobRevenue;
    }
    public BigDecimal getTpowerCost() {
        return this.tpowerCost;
    }
    
    public void setTpowerCost(BigDecimal tpowerCost) {
        this.tpowerCost = tpowerCost;
    }
    public BigDecimal getDamageCost() {
        return this.damageCost;
    }
    
    public void setDamageCost(BigDecimal damageCost) {
        this.damageCost = damageCost;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


