package h.entities;
// Generated 29-Feb-2012 13:51:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cpu generated by hbm2java
 */
public class Cpu  implements java.io.Serializable {


     private Integer cpuid;
     private Job job;
     private Processingrate processingrate;
     private Health health;
     private String name;
     private Set pmap2s = new HashSet(0);
     private Set plants = new HashSet(0);
     private Set thermalmaps = new HashSet(0);
     private Set schedules = new HashSet(0);
     private Set pmap1s = new HashSet(0);
     private Set costplans = new HashSet(0);
     private Set pschedules = new HashSet(0);

    public Cpu() {
    }

    public Cpu(Job job, Processingrate processingrate, Health health, String name, Set pmap2s, Set plants, Set thermalmaps, Set schedules, Set pmap1s, Set costplans, Set pschedules) {
       this.job = job;
       this.processingrate = processingrate;
       this.health = health;
       this.name = name;
       this.pmap2s = pmap2s;
       this.plants = plants;
       this.thermalmaps = thermalmaps;
       this.schedules = schedules;
       this.pmap1s = pmap1s;
       this.costplans = costplans;
       this.pschedules = pschedules;
    }
   
    public Integer getCpuid() {
        return this.cpuid;
    }
    
    public void setCpuid(Integer cpuid) {
        this.cpuid = cpuid;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }
    public Processingrate getProcessingrate() {
        return this.processingrate;
    }
    
    public void setProcessingrate(Processingrate processingrate) {
        this.processingrate = processingrate;
    }
    public Health getHealth() {
        return this.health;
    }
    
    public void setHealth(Health health) {
        this.health = health;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getPmap2s() {
        return this.pmap2s;
    }
    
    public void setPmap2s(Set pmap2s) {
        this.pmap2s = pmap2s;
    }
    public Set getPlants() {
        return this.plants;
    }
    
    public void setPlants(Set plants) {
        this.plants = plants;
    }
    public Set getThermalmaps() {
        return this.thermalmaps;
    }
    
    public void setThermalmaps(Set thermalmaps) {
        this.thermalmaps = thermalmaps;
    }
    public Set getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set schedules) {
        this.schedules = schedules;
    }
    public Set getPmap1s() {
        return this.pmap1s;
    }
    
    public void setPmap1s(Set pmap1s) {
        this.pmap1s = pmap1s;
    }
    public Set getCostplans() {
        return this.costplans;
    }
    
    public void setCostplans(Set costplans) {
        this.costplans = costplans;
    }
    public Set getPschedules() {
        return this.pschedules;
    }
    
    public void setPschedules(Set pschedules) {
        this.pschedules = pschedules;
    }




}


