package h.entities;
// Generated 29-Feb-2012 13:51:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Health generated by hbm2java
 */
public class Health  implements java.io.Serializable {


     private Integer hid;
     private Integer status;
     private Set cpus = new HashSet(0);

    public Health() {
    }

    public Health(Integer status, Set cpus) {
       this.status = status;
       this.cpus = cpus;
    }
   
    public Integer getHid() {
        return this.hid;
    }
    
    public void setHid(Integer hid) {
        this.hid = hid;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getCpus() {
        return this.cpus;
    }
    
    public void setCpus(Set cpus) {
        this.cpus = cpus;
    }




}


