package h.entities;
// Generated 29-Feb-2012 13:51:12 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Job generated by hbm2java
 */
public class Job  implements java.io.Serializable {


     private Integer jid;
     private BigDecimal revenue;
     private Date time;
     private BigDecimal duration;
     private Integer priority;
     private Integer cpuid;
     private BigDecimal processingrate;
     private Integer active;
     private Set plants = new HashSet(0);
     private Set cpus = new HashSet(0);
     private Set costplans = new HashSet(0);

    public Job() {
    }

    public Job(BigDecimal revenue, Date time, BigDecimal duration, Integer priority, Integer cpuid, BigDecimal processingrate, Integer active, Set plants, Set cpus, Set costplans) {
       this.revenue = revenue;
       this.time = time;
       this.duration = duration;
       this.priority = priority;
       this.cpuid = cpuid;
       this.processingrate = processingrate;
       this.active = active;
       this.plants = plants;
       this.cpus = cpus;
       this.costplans = costplans;
    }
   
    public Integer getJid() {
        return this.jid;
    }
    
    public void setJid(Integer jid) {
        this.jid = jid;
    }
    public BigDecimal getRevenue() {
        return this.revenue;
    }
    
    public void setRevenue(BigDecimal revenue) {
        this.revenue = revenue;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public BigDecimal getDuration() {
        return this.duration;
    }
    
    public void setDuration(BigDecimal duration) {
        this.duration = duration;
    }
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    public Integer getCpuid() {
        return this.cpuid;
    }
    
    public void setCpuid(Integer cpuid) {
        this.cpuid = cpuid;
    }
    public BigDecimal getProcessingrate() {
        return this.processingrate;
    }
    
    public void setProcessingrate(BigDecimal processingrate) {
        this.processingrate = processingrate;
    }
    public Integer getActive() {
        return this.active;
    }
    
    public void setActive(Integer active) {
        this.active = active;
    }
    public Set getPlants() {
        return this.plants;
    }
    
    public void setPlants(Set plants) {
        this.plants = plants;
    }
    public Set getCpus() {
        return this.cpus;
    }
    
    public void setCpus(Set cpus) {
        this.cpus = cpus;
    }
    public Set getCostplans() {
        return this.costplans;
    }
    
    public void setCostplans(Set costplans) {
        this.costplans = costplans;
    }




}


