package h.entities;
// Generated 29-Feb-2012 13:51:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mode generated by hbm2java
 */
public class Mode  implements java.io.Serializable {


     private Integer modeId;
     private String name;
     private Date timeStarted;
     private Set rows = new HashSet(0);

    public Mode() {
    }

	
    public Mode(Date timeStarted) {
        this.timeStarted = timeStarted;
    }
    public Mode(String name, Date timeStarted, Set rows) {
       this.name = name;
       this.timeStarted = timeStarted;
       this.rows = rows;
    }
   
    public Integer getModeId() {
        return this.modeId;
    }
    
    public void setModeId(Integer modeId) {
        this.modeId = modeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getTimeStarted() {
        return this.timeStarted;
    }
    
    public void setTimeStarted(Date timeStarted) {
        this.timeStarted = timeStarted;
    }
    public Set getRows() {
        return this.rows;
    }
    
    public void setRows(Set rows) {
        this.rows = rows;
    }




}


