package h.entities;
// Generated 29-Feb-2012 13:51:12 by Hibernate Tools 3.2.1.GA



/**
 * Plant generated by hbm2java
 */
public class Plant  implements java.io.Serializable {


     private Integer plid;
     private Thermalmap thermalmap;
     private Job job;
     private Schedule schedule;
     private Pmap2 pmap2;
     private Row row;
     private Pmap1 pmap1;
     private Cpu cpu;
     private Pschedule pschedule;

    public Plant() {
    }

    public Plant(Thermalmap thermalmap, Job job, Schedule schedule, Pmap2 pmap2, Row row, Pmap1 pmap1, Cpu cpu, Pschedule pschedule) {
       this.thermalmap = thermalmap;
       this.job = job;
       this.schedule = schedule;
       this.pmap2 = pmap2;
       this.row = row;
       this.pmap1 = pmap1;
       this.cpu = cpu;
       this.pschedule = pschedule;
    }
   
    public Integer getPlid() {
        return this.plid;
    }
    
    public void setPlid(Integer plid) {
        this.plid = plid;
    }
    public Thermalmap getThermalmap() {
        return this.thermalmap;
    }
    
    public void setThermalmap(Thermalmap thermalmap) {
        this.thermalmap = thermalmap;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }
    public Schedule getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(Schedule schedule) {
        this.schedule = schedule;
    }
    public Pmap2 getPmap2() {
        return this.pmap2;
    }
    
    public void setPmap2(Pmap2 pmap2) {
        this.pmap2 = pmap2;
    }
    public Row getRow() {
        return this.row;
    }
    
    public void setRow(Row row) {
        this.row = row;
    }
    public Pmap1 getPmap1() {
        return this.pmap1;
    }
    
    public void setPmap1(Pmap1 pmap1) {
        this.pmap1 = pmap1;
    }
    public Cpu getCpu() {
        return this.cpu;
    }
    
    public void setCpu(Cpu cpu) {
        this.cpu = cpu;
    }
    public Pschedule getPschedule() {
        return this.pschedule;
    }
    
    public void setPschedule(Pschedule pschedule) {
        this.pschedule = pschedule;
    }




}


