package h.entities;
// Generated 29-Feb-2012 13:51:12 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pschedule generated by hbm2java
 */
public class Pschedule  implements java.io.Serializable {


     private Integer pscid;
     private Cpu cpu;
     private Date time;
     private BigDecimal totalRevenue;
     private Set plants = new HashSet(0);

    public Pschedule() {
    }

    public Pschedule(Cpu cpu, Date time, BigDecimal totalRevenue, Set plants) {
       this.cpu = cpu;
       this.time = time;
       this.totalRevenue = totalRevenue;
       this.plants = plants;
    }
   
    public Integer getPscid() {
        return this.pscid;
    }
    
    public void setPscid(Integer pscid) {
        this.pscid = pscid;
    }
    public Cpu getCpu() {
        return this.cpu;
    }
    
    public void setCpu(Cpu cpu) {
        this.cpu = cpu;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public BigDecimal getTotalRevenue() {
        return this.totalRevenue;
    }
    
    public void setTotalRevenue(BigDecimal totalRevenue) {
        this.totalRevenue = totalRevenue;
    }
    public Set getPlants() {
        return this.plants;
    }
    
    public void setPlants(Set plants) {
        this.plants = plants;
    }




}


