package h.entities;
// Generated 29-Feb-2012 13:51:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Row generated by hbm2java
 */
public class Row  implements java.io.Serializable {


     private Integer rowId;
     private Mode mode;
     private String name;
     private Set plants = new HashSet(0);
     private Set thermalmaps = new HashSet(0);
     private Set pmap2s = new HashSet(0);
     private Set pmap1s = new HashSet(0);

    public Row() {
    }

    public Row(Mode mode, String name, Set plants, Set thermalmaps, Set pmap2s, Set pmap1s) {
       this.mode = mode;
       this.name = name;
       this.plants = plants;
       this.thermalmaps = thermalmaps;
       this.pmap2s = pmap2s;
       this.pmap1s = pmap1s;
    }
   
    public Integer getRowId() {
        return this.rowId;
    }
    
    public void setRowId(Integer rowId) {
        this.rowId = rowId;
    }
    public Mode getMode() {
        return this.mode;
    }
    
    public void setMode(Mode mode) {
        this.mode = mode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getPlants() {
        return this.plants;
    }
    
    public void setPlants(Set plants) {
        this.plants = plants;
    }
    public Set getThermalmaps() {
        return this.thermalmaps;
    }
    
    public void setThermalmaps(Set thermalmaps) {
        this.thermalmaps = thermalmaps;
    }
    public Set getPmap2s() {
        return this.pmap2s;
    }
    
    public void setPmap2s(Set pmap2s) {
        this.pmap2s = pmap2s;
    }
    public Set getPmap1s() {
        return this.pmap1s;
    }
    
    public void setPmap1s(Set pmap1s) {
        this.pmap1s = pmap1s;
    }




}


