package h.entities;
// Generated 29-Feb-2012 13:51:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rules generated by hbm2java
 */
public class Rules  implements java.io.Serializable {


     private Integer rid;
     private String con;
     private Set userses = new HashSet(0);

    public Rules() {
    }

    public Rules(String con, Set userses) {
       this.con = con;
       this.userses = userses;
    }
   
    public Integer getRid() {
        return this.rid;
    }
    
    public void setRid(Integer rid) {
        this.rid = rid;
    }
    public String getCon() {
        return this.con;
    }
    
    public void setCon(String con) {
        this.con = con;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


