package h.entities;
// Generated 29-Feb-2012 13:51:12 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


     private Integer scid;
     private Cpu cpu;
     private Date time;
     private BigDecimal totalRevenue;
     private Set plants = new HashSet(0);

    public Schedule() {
    }
    public Schedule(int i, int y){

    }
    public Schedule(Cpu cpu, Date time, BigDecimal totalRevenue, Set plants) {
       this.cpu = cpu;
       this.time = time;
       this.totalRevenue = totalRevenue;
       this.plants = plants;
    }
   
    public Integer getScid() {
        return this.scid;
    }
    
    public void setScid(Integer scid) {
        this.scid = scid;
    }
    public Cpu getCpu() {
        return this.cpu;
    }
    
    public void setCpu(Cpu cpu) {
        this.cpu = cpu;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public BigDecimal getTotalRevenue() {
        return this.totalRevenue;
    }
    
    public void setTotalRevenue(BigDecimal totalRevenue) {
        this.totalRevenue = totalRevenue;
    }
    public Set getPlants() {
        return this.plants;
    }
    
    public void setPlants(Set plants) {
        this.plants = plants;
    }




}


