package h.entities;
// Generated 29-Feb-2012 13:51:12 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Totalpower generated by hbm2java
 */
public class Totalpower  implements java.io.Serializable {


     private Integer tpid;
     private BigDecimal totalPower;
     private BigDecimal pue;
     private Set userses = new HashSet(0);
     private Set costplans = new HashSet(0);

    public Totalpower() {
    }

    public Totalpower(BigDecimal totalPower, BigDecimal pue, Set userses, Set costplans) {
       this.totalPower = totalPower;
       this.pue = pue;
       this.userses = userses;
       this.costplans = costplans;
    }
   
    public Integer getTpid() {
        return this.tpid;
    }
    
    public void setTpid(Integer tpid) {
        this.tpid = tpid;
    }
    public BigDecimal getTotalPower() {
        return this.totalPower;
    }
    
    public void setTotalPower(BigDecimal totalPower) {
        this.totalPower = totalPower;
    }
    public BigDecimal getPue() {
        return this.pue;
    }
    
    public void setPue(BigDecimal pue) {
        this.pue = pue;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }
    public Set getCostplans() {
        return this.costplans;
    }
    
    public void setCostplans(Set costplans) {
        this.costplans = costplans;
    }




}


