package h.entities;
// Generated 29-Feb-2012 13:51:12 by Hibernate Tools 3.2.1.GA



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer usid;
     private Costplan costplan;
     private Totalpower totalpower;
     private Rules rules;
     private Teams teams;
     private String name;
     private Integer level;

    public Users() {
    }

    public Users(Costplan costplan, Totalpower totalpower, Rules rules, Teams teams, String name, Integer level) {
       this.costplan = costplan;
       this.totalpower = totalpower;
       this.rules = rules;
       this.teams = teams;
       this.name = name;
       this.level = level;
    }
   
    public Integer getUsid() {
        return this.usid;
    }
    
    public void setUsid(Integer usid) {
        this.usid = usid;
    }
    public Costplan getCostplan() {
        return this.costplan;
    }
    
    public void setCostplan(Costplan costplan) {
        this.costplan = costplan;
    }
    public Totalpower getTotalpower() {
        return this.totalpower;
    }
    
    public void setTotalpower(Totalpower totalpower) {
        this.totalpower = totalpower;
    }
    public Rules getRules() {
        return this.rules;
    }
    
    public void setRules(Rules rules) {
        this.rules = rules;
    }
    public Teams getTeams() {
        return this.teams;
    }
    
    public void setTeams(Teams teams) {
        this.teams = teams;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }




}


